export  {default as Bmw } from './Bmw.jpg'
export  {default as Bugatti } from './Bugatti.jpg'
export  {default as Chevrolet } from './Chevrolet.jpg'
export  {default as Lambo } from './Lambo.jpg'
export  {default as Mers } from './Mers.jpg'
export  {default as Mustang } from './Mustang.jpg'
export  {default as Rolls } from './Rolls.jpg'
export  {default as Tesla } from './Tesla.jpg'